name: Daily NSE to Redis Sync

on:
  schedule:
    #- cron: "0 1 * * *"    # Runs every day at 01:00 AM UTC
    - cron: "*/1 * * * *"    # Every minute
  workflow_dispatch:        # Allows you to trigger it manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas redis nselib python-dotenv

      - name: Run sync script
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: python sync_to_redis.py
